import React,{useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import "./style.css";
const fmt=n=>Number(n).toFixed(2), pct=n=>`${(Number(n)*100).toFixed(1)}%`;
const icon={Goals:"⚽",Corners:"🚩","Team Corners":"🚩",Cards:"🟨","Card Handicap":"🟨","Player Card":"🟨","Player Shots":"🎯","Shots on Target":"🎯",BTTS:"⚽","BTTS 1st Half":"⚽","Match Result":"🏆"};
function App(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[min,setMin]=useState(3),[market,setMarket]=useState("ALL"),[conf,setConf]=useState("ALL");
 async function scan(){setLoading(true);setError("");try{const r=await fetch("/api/scanner");const j=await r.json();if(!r.ok)throw new Error(j.error||"API request failed");setData(j)}catch(e){setError(e.message)}finally{setLoading(false)}}
 const rows=useMemo(()=> (data?.results||[]).filter(x=>x.value*100>=Number(min)).filter(x=>market==="ALL"||x.marketKey===market).filter(x=>conf==="ALL"||x.confidence===conf),[data,min,market,conf]);
 const markets=[["ALL","All markets"],...Array.from(new Map((data?.results||[]).map(x=>[x.marketKey,x.market])).entries())];
 return <div className="app"><header><div><div className="eyebrow">LIVE FOOTBALL VALUE ENGINE</div><h1>Bet Scanner <span>2.0</span></h1><p>Goals • Corners • Shots • SOT • Cards • BTTS</p></div><button onClick={scan} disabled={loading}>{loading?"SCANNING…":"SCAN NOW"}</button></header>
 <section className="stats"><div><b>{rows.length}</b><small>VALUE BETS</small></div><div><b>{data?.eventsScanned||0}</b><small>GAMES SCANNED</small></div><div><b>{data?.quota?.remaining??"—"}</b><small>CREDITS LEFT</small></div></section>
 <section className="controls"><label>MIN VALUE <input type="number" min="0" step=".5" value={min} onChange={e=>setMin(e.target.value)}/>%</label><label>MARKET <select value={market} onChange={e=>setMarket(e.target.value)}>{markets.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>CONFIDENCE <select value={conf} onChange={e=>setConf(e.target.value)}><option>ALL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></label></section>
 {error&&<div className="error">{error}</div>}
 <div className="explain">Fair odds = margin-adjusted consensus probability from the available bookmaker quotes. Confidence is a transparent ranking heuristic based on value, probability and number of books — <b>not a prediction guarantee</b>.</div>
 <main>{rows.length===0&&!loading?<div className="empty">{data?"No value bets match your filters. Try 0–3% or All markets.":"Press SCAN NOW to scan."}</div>:rows.map(r=><article className="card" key={r.id}><div className="top"><span className="tag">{icon[r.market]||"•"} {r.market}</span><span className={`confidence ${r.confidence.toLowerCase()}`}>{r.confidence}</span></div><h2>{r.selection}{r.point!==null&&r.point!==undefined?` ${r.point}`:""}</h2><p className="game">{r.home} <b>vs</b> {r.away}</p><div className="grid"><div><small>BEST ODDS</small><strong>{fmt(r.odds)}</strong><em>{r.bookmaker}</em></div><div><small>FAIR ODDS</small><strong>{fmt(r.fairOdds)}</strong></div><div><small>PROBABILITY</small><strong>{pct(r.probability)}</strong></div><div><small>VALUE</small><strong className="green">+{(r.value*100).toFixed(1)}%</strong></div></div></article>)}</main>
 <footer>{data?.quota?.remaining!==null&&data?.quota?.remaining!==undefined?`API credits remaining: ${data.quota.remaining} • `:""}Markets depend on bookmaker coverage.</footer></div>}
createRoot(document.getElementById("root")).render(<App/>);