import React,{useEffect,useMemo,useState} from "react";import{createRoot}from"react-dom/client";import"./style.css";
const major=[["major","⭐ Major Leagues"],["soccer_epl","Premier League"],["soccer_spain_la_liga","La Liga"],["soccer_germany_bundesliga","Bundesliga"],["soccer_italy_serie_a","Serie A"],["soccer_france_ligue_one","Ligue 1"],["soccer_uefa_champs_league","Champions League"],["soccer_uefa_europa_league","Europa League"],["soccer_netherlands_eredivisie","Eredivisie"],["soccer_portugal_primeira_liga","Primeira Liga"],["soccer_spl","Scottish Premiership"],["soccer_efl_champ","Championship"],["soccer_usa_mls","MLS"],["all","All available soccer leagues"]];
const markets=[["result","Match Result"],["goals","Goals O/U"],["btts","BTTS"],["corners","Corners"],["cards","Cards"],["shots","Player Shots"],["sot","Shots on Target"],["player_cards","Player Cards"]];
const fmtTime=d=>new Date(d).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});const fmtDate=d=>new Date(d).toLocaleDateString([],{weekday:"short",day:"2-digit",month:"short"});
function App(){const today=new Date();const [from,setFrom]=useState(today.toISOString().slice(0,10)),[to,setTo]=useState(today.toISOString().slice(0,10)),[league,setLeague]=useState("major"),[market,setMarket]=useState("all"),[min,setMin]=useState(3),[conf,setConf]=useState("ALL"),[maxGames,setMaxGames]=useState(8),[rows,setRows]=useState([]),[meta,setMeta]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
async function scan(){setLoading(true);setError("");try{const m=market==="all"?markets.map(x=>x[0]).join(","):market;const u=`/api/scanner?from=${from}&to=${to}&league=${league}&markets=${m}&minValue=${min}&maxGames=${maxGames}`;const r=await fetch(u),j=await r.json();if(!r.ok)throw Error(j.error||"Scan failed");setRows(j.rows||[]);setMeta(j)}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{scan()},[]);
const shown=useMemo(()=>rows.filter(r=>conf==="ALL"||r.confidence===conf),[rows,conf]);
return <div className="app"><header><div><div className="eyebrow">LIVE FOOTBALL VALUE ENGINE</div><h1>Bet Scanner <b>3.0</b></h1><p>Goals • Corners • Shots • SOT • Cards • BTTS • Value</p></div><button onClick={scan} disabled={loading}>{loading?"SCANNING…":"SCAN NOW"}</button></header>
<section className="filters"><div><label>FROM</label><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div><label>TO</label><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><div><label>LEAGUE</label><select value={league} onChange={e=>setLeague(e.target.value)}>{major.map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></div><div><label>MARKET</label><select value={market} onChange={e=>setMarket(e.target.value)}><option value="all">All markets</option>{markets.map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></div><div><label>MIN VALUE</label><input type="number" min="0" step=".5" value={min} onChange={e=>setMin(e.target.value)}/></div><div><label>MAX GAMES</label><select value={maxGames} onChange={e=>setMaxGames(e.target.value)}>{[4,6,8,10,12,16].map(n=><option key={n}>{n}</option>)}</select></div><div><label>CONFIDENCE</label><select value={conf} onChange={e=>setConf(e.target.value)}><option>ALL</option><option>VERY HIGH</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></div></section>
{error&&<div className="error">{error}</div>}<section className="stats"><div><strong>{shown.length}</strong><span>VALUE BETS</span></div><div><strong>{meta?.gamesFound??0}</strong><span>GAMES FOUND</span></div><div><strong>{meta?.eventsScanned??0}</strong><span>GAMES SCANNED</span></div></section>
<div className="warning">Fair odds = margin-adjusted bookmaker consensus. Specialist markets depend on bookmaker/league coverage. <b>Not a prediction guarantee.</b></div>
<main>{shown.length===0&&!loading?<div className="empty">No value bets match these filters. Try a lower value threshold, another league, or “All markets”.</div>:shown.map(r=><article className="card" key={r.id}><div className="top"><div><span className="tag">{r.marketLabel}</span><span className="league">{r.league}</span><h2>{r.selection}</h2><p>{r.home} <b>vs</b> {r.away}</p></div><div className={`confidence ${r.confidence.replace(" ","-").toLowerCase()}`}>{r.confidence}</div></div><div className="event"><span>📅 {fmtDate(r.commence_time)}</span><span>🕒 {fmtTime(r.commence_time)}</span><span>🏟️ {r.home} v {r.away}</span></div><div className="grid"><div><small>BEST ODDS</small><strong>{r.odds.toFixed(2)}</strong><em>{r.bookmaker}</em></div><div><small>FAIR ODDS</small><strong>{r.fairOdds.toFixed(2)}</strong></div><div><small>PROBABILITY</small><strong>{(r.probability*100).toFixed(1)}%</strong></div><div><small>VALUE</small><strong className="green">+{(r.value*100).toFixed(1)}%</strong></div></div><div className="meta">Point: {r.point||"—"} • Books compared: {r.books}</div></article>)}</main><footer>Bet Scanner 3.0 • API data only • Check bookmaker market status before betting.</footer></div>}createRoot(document.getElementById("root")).render(<App/>);